### ISSUE TITLE
HowMuchMoneyDoIHave coffee script

### ISSUE THREAD

**Issue by jacksob3** [XeroAPI/HeyXero#2]
Firstly, let me say this is excellent, and after brief amount of config and learning about Heroku I got this working on our live Xero and Slack channels and it works a treat - If I can work out how to add a query for Sales MTD and sales in last day and total owed and owing I might not need to leave slack again!  This would be a great bot to have provide a summary report at a defined time each morning so everyone is on the same page.

While the "who owes" and "who do I owe" have multiple responses returned, I only get a single response for bank accounts in the HowMuch do I owe whereas I have about 5 bank accounts of which 3 are active on Xero.  I have had a quick look at the script and it appears to be expecting to handle multiple bank accounts in the response, but I cannot see why it is not bringing those back.  Happy to share the details over chat if that helps troubleshoot!

Cheers, Brent at shelfco.com.au

**Comment by nicholasjgreen** [comment]
Hi @jacksob3 , thanks for the awesome feedback. I'll have a look at the code for the HowMuchMoneyDoIHave request this week, I don't think it will take too long to sort out. I'm pretty sure that we have the data, we just haven't formatted the user response to handle it. What I'm considering doing is listing each bank account with their balance and then a grand total at the end. Is that what you would expect?

**Comment by Xero-ScottPotter** [comment]
Yea the HowMuchMoneyDoIHave problem was a pretty simple fix in the parsing of the response, we just merged the fix in so you should be able to pull down the latest changes, push to heroku, and be all set. :+1: 

Really cool that you're getting some value out of it! And thanks for the suggestions, we'll definitely keep them in mind if we have a chance to put some more time into this project.

**Comment by nicholasjgreen** [comment]
Nailed it @Xero-ScottPotter

**Comment by jacksob3** [comment]
Awesome guys will work through the pulling and pushing and give it a go, well done.  Will be able to share with my team now, and perfect timing for the start of a new financial year!

**Comment by jacksob3** [comment]
Great, worked perfectly, thanks!

**Comment by jacksob3** [comment]
Just for info - I connected this to a Zapier set of zaps that sends a set of messages to a slack channel at 6am each morning, so by the time my team wakes  these three queries are sitting in the feed ready to start the day - only minor issue is I had to send the first query twice as the bot has to first wake up, not elegant but works - the other three queries I am thinking of would be:
Sales for the last day and MTD (as provides a snapshot of how the revenues are going)
% sales v monthly budget and possibly % sales MTD/Budget MTD (may be well outside my coding capabilities, but to be able to understand how the sales to date in a month matches the day vs monthly budget target is something I calc every day!)
Top 5 -  customer sales over last day (as a reminder to followup, thanks etc)
If I get these working will push to you for review, cheers, Brent
